### PR TITLE
chore: update jest to v25.5.4

### PR DESCRIPTION
**Pull request by apapko**
Address  #145. 

W-7679855

### CODE REVIEW

**Comment by apapko** [comment]
Copying comment from closed #151 by @ekashida 
Verified together that the error no longer occurs with the jest version bump. However, @salesforce/wire-service-jest-util has only a dev dependency on jest so I'm confused about what exactly we're fixing with this change.

**Comment by apapko** [comment]
My thinking was that bc sfdx-lwc-jest dependency in [package-lock](https://github.com/trailheadapps/lwc-recipes/blob/master/package-lock.json#L1263) of lwc-recipes repo specifies "@salesforce/wire-service-jest-util" version 26.0.1 but the jest version 24.9.0, there will be a mismatch lead to abnormality.

**Comment by ekashida** [comment]
I think we need to understand the root cause before we can call this fixed, or at the very least come up with a test that would prevent the same issue from occurring. I'm a little worried that things break unless we bump the jest version from `24.9.0` to `26.0.1` but our lwc-test peer dependency requires a minimum jest version of [24.9.0](https://github.com/salesforce/lwc-test/blob/ef522ba6bcedb6747967b9353b6488e7b3d4a0e4/packages/%40lwc/jest-preset/package.json#L18).

A quick scan seems to indicate that `@salesforce@wire-service-jest-util` does not invoke any jest APIs. @jodarove can you confirm this?

**Comment by jodarove** [comment]
@ekashida to the best of my knowledge `@salesfoce/wire-service-jest-util` (2.2.6 from yarn.lock) does not invoke any jest api.

**Comment by apapko** [comment]
Per offline conversation with @ekashida @ravijayaramappa @trevor-bliss @jodarove, pinning the jest version to 25.5.4. The same will be applied to lwc-test projects.

**Comment by apapko** [comment]
@jbleyleSF do we need to make a post/announcement to notify external developers about a major jest upgrade in this change?

**Pull request merged**
