### PR TITLE
feat: prepare for spring21 release

### PR DESCRIPTION
**Pull request by ravijayaramappa**
update lwc to 1.9.3-230.1 and @lwc/jest* to 9.0.0-230.0
update API version to 51.0

### CODE REVIEW

**Review by jodarove — APPROVED** [review]
LGTM; though let's wait for @trevor-bliss review. Also, I'm wondering if we should include the [new skipApiVersionCheck flag](https://github.com/salesforce/sfdx-lwc-jest/commit/6f7052b891335c602bebd8c15249fdbb2c253916)

**Comment by trevor-bliss** [comment]
Yeah I think we should include the skipApiVersionCheck flag as well as PM's dependency upgrades https://github.com/salesforce/sfdx-lwc-jest/commit/10137744d07a86bfa8b2eeb85cab82177a84acf9.

**Comment by ravijayaramappa** [comment]
@trevor-bliss The dependency upgrade change is labeled breaking because it introduces Jest 26. Kevin Hill wanted some messaging to go out before we did that upgrade.
We can cherry-pick the skipApiVersionCheck change on to this branch. Let's get this version out and we can do a follow up release. Thoughts?

**Comment by trevor-bliss** [comment]
@ravijayaramappa Fine with me. Let's also merge and cherry-pick this one as well though. It provides additional documentation around the new flag I think is important. https://github.com/salesforce/sfdx-lwc-jest/pull/190

**Pull request merged**
