### PR TITLE
v4.1.0

### PR DESCRIPTION
**Pull request by rax-it**

### CODE REVIEW

**Comment by nolanlawson** [comment]
@rax-it This is for CLCO, right? Maybe we should merge with #355 and do a major version bump in one go.

**Comment by rax-it** [comment]
> @rax-it This is for CLCO, right? Maybe we should merge with #355 and do a major version bump in one go.

Sure, I couldn't figure out the `how to publish` part as well.

**Comment by nolanlawson** [comment]
@rax-it No worries, I can do the publish.

**Comment by nolanlawson** [comment]
Superseded by #356

**Pull request closed without merging**
