### PR TITLE
add stub. modalBody, modalHeader, modalFooter

### PR DESCRIPTION
**Pull request by noblejasper**
test fails when using modal-body, modal-header, modal-footer components
Added stub to prevent test from failing

### CODE REVIEW

**Comment by crysislinux** [comment]
Is the `lightning/modal` also needed?

**Comment by noblejasper** [comment]
@crysislinux No, the component `lightning/modal` does not exist and is therefore not needed.

**Review by alex-bolsoy — APPROVED** [review]

**Comment by CollinHerber** [comment]
Can we get some traction on this please, it is rather cumbersome to add these stubs to every repo to test against LightningModal related components.

**Review by Templarian — APPROVED** [review]

**Comment by Templarian** [comment]
@CollinHerber Latest NPM has it published.

**Comment by CollinHerber** [comment]
> @CollinHerber Latest NPM has it published.

Thank you.

**Pull request merged**
